typography_spectrum: 0.8743289227131754
color:
  brandStrength: 0.3767806300893426
  lightness: 0.4039959053043276
  saturation: 0.07400357071310282
  rhythmicContrast: 0.1484786462970078
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.8428650870919228
author:
  email: Carmen@MCDJCompany.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7b851b90-ec58-4689-aa05-f310eb2d1ac5.png
name: 'MC DJ Company, LLC'
title: Look No Further - Your Party Just Started.
description: Entertainment | Lighting | Creativity
